apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base
  - configmap-output.yaml
patches:
  - patch: |-
      - op: replace
        path: /data/Exclude_Path
        value: /var/log/containers/falco-*.log,/var/log/containers/tetragon-*.log,/var/log/containers/kyverno-*.log,/var/log/containers/*_kube-system_*.log,/var/log/containers/*_elastic-system_*.log,/var/log/containers/*_kafka_*.log,/var/log/containers/*_local-path-storage_*.log,/var/log/containers/*_cert-manager_*.log
    target:
      kind: ConfigMap
      name: fluent-bit-config-common
configMapGenerator: []
